import React, { useEffect } from "react";
import "./Bars.css";

// bar will generated by this value
const BARS_COUNT = 150;
const PRIMARY_COLOR = "lightpink";

function Bars(props) {

  //  whenenver component gets render bar will generate
  useEffect(() => {
      resetArray();
  }, []);  
  
  function resetArray() {
    const array = [];
    for (let i = 0; i < BARS_COUNT; i++) {
      const randomVal = Math.floor(Math.random() * BARS_COUNT);
      array.push(Math.max(5, randomVal));
    }
    props.setrandomHeights(array);
  }


  return (
    <div className="bars-container">
      <button type="button" className="generator" onClick={resetArray}>Generate New Bar</button>
      <div className="bars-wrapper">
          {
            props.randomHeights.map((value , idx) => (
               <div 
                  className="bars"
                  key={idx}
                  style={{
                    height: `${value}px`,
                    width : `3px`,
                    backgroundColor: PRIMARY_COLOR,
                    margin: '1px',
                  }}
                >
               </div>
            ))
          }
      </div>   
    </div>
  )
}

export default Bars;
