import React from "react";
import Navbar from "../header/Sidebar";
import "./Bars.css";

// bar will generated by this value
const BARS_COUNT = 100;
const PRIMARY_COLOR = "lightblue";

function Bars(props) {
  

 

  function resetArray() {
    const array = [];
    for (let i = 0; i < BARS_COUNT; i++) {
      const randomVal = Math.floor(Math.random() * BARS_COUNT);
      array.push(Math.max(5, randomVal));
    }
    props.setrandomHeights(array);
    
    // setting up background color: ;
    const bars = document.querySelectorAll('.bars');

    for(var i = 0; i < bars.length; i++) {
      bars[i].style.backgroundColor = PRIMARY_COLOR;
    }
  }


  return (
    <div className="bars-container">
      <section id="sidebar" ref={props.sidebarRef}>
          
         <button type="button" className="generator" onClick={resetArray}>Generate New Bar</button>
         <div className="sidebar-container">
            
            <Navbar randomHeights={props.randomHeights} setShowSidebar={props.setShowSidebar}/>
         </div>
      </section>
      <section className="bars-wrapper">
          {
            props.randomHeights.map((value , idx) => (
               <div 
                  className="bars"
                  key={idx}
                  style={{
                    height: `${value}px`,
                    width : '5px',
                    backgroundColor : PRIMARY_COLOR,
                    margin: '1px',
                    position: 'relative',
                    transition : 'height .2s ease-in-out'
                  }}
                >
               </div>
            ))
          }
      </section>   
    </div>
  )
}

export default Bars;
